package ntnu.idata2302.sfp.server.util;

import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Thread-safe ID allocator used by the server to hand out small integer IDs.
 *
 * <p>This utility reuses IDs returned via {@link #release(int)} by keeping them
 * in a concurrent queue; when no freed IDs are available it generates a new ID
 * using an {@link AtomicInteger} counter.</p>
 *
 * <p>Implementation notes:
 * <ul>
 *   <li>Methods are safe for concurrent use by multiple threads.</li>
 *   <li>IDs generated by the counter-start at {@code 2} (the initial value of {@code nextId}).</li>
 *   <li>Callers must avoid releasing the same ID multiple times — doing so may
 *       result in duplicate allocations.</li>
 * </ul>
 * </p>
 */
public class IdAllocator {

  private static AtomicInteger nextId = new AtomicInteger(2); // IDs start at 2
  private static ConcurrentLinkedQueue<Integer> freeIds = new ConcurrentLinkedQueue<>();

  /**
   * Allocate an ID.
   *
   * <p>If a previously released ID is available, it will be reused (FIFO
   * order). Otherwise, a new ID is returned by incrementing the internal
   * counter.</p>
   *
   * @return a non-negative integer ID (generated IDs start from {@code 2})
   * @implNote This method is thread-safe; it may return an ID
   */
  public static int allocate() {
    Integer id = freeIds.poll();
    if (id != null) {
      return id; // reuse freed id
    }
    return nextId.getAndIncrement(); // generate new id
  }

  /**
   * Release an ID back to the pool for reuse.
   *
   * <p>The released ID will be available for subsequent {@link #allocate()}
   * calls. Callers should only release IDs that were previously allocated
   * and should avoid releasing the same ID multiple times to prevent duplicate
   * allocations.</p>
   *
   * @param id the ID to release; behavior is undefined if the same {@code id}
   *           is released multiple times or if an ID that was not allocated is released
   */
  public static void release(int id) {
    freeIds.offer(id); // return id to pool
  }
}